### ISSUE TITLE
Implement `NotLike` value comparator.

### ISSUE THREAD

**Issue by ggomarighetti** [turkraft/springfilter#328]
Following the same logic applied for `equal`, `notEqual`, `isEmpty`, `isNotEmpty`, `isNull`, `isNotNull`, the only comparator that was not reached by this standard was `like`.

It has an added value when implementing the library in languages where there is not yet an official Query Builder (in my case C#).

**Comment by torshid** [comment]
Hey @ggomarighetti,

Not sure which version you're using, but following operators are planned to be implemented in the next version of branch 3.x,x when I find time for it:
* `like`, equivalent to `~`
* `ilike`, equivalent to `~~`
* `not like`, equivalent to `not ... ~ ...`
* `not ilike` , equivalent to `not ... ~~ ...`

You can always [sponsor the project](https://github.com/sponsors/torshid) to speedup things so that everyone can enjoy these new features. :)
